/* Project Euler - Problem #2

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

*/

#include <stdio.h>

int main(void) {
	/*
	i + prev = val;
	0 + 1 = 1;
	1 + 1 = 2;
	1 + 2 = 3;
	2 + 3 = 5;
	3 + 5 = 8;
	5 + 8 = 13;
	*/

	int i = 1;
	int prev = 0;
	int sum = 0;

	while (prev + i < 4000000) {
		int val = prev + i;
		prev = i;
		i = val;

		if (val % 2 == 0) {
			sum += val;
		}

		printf("%i, ", val);
	}

	printf("\nsum = %i\n", sum);

	return;
}